### ISSUE TITLE
触发ID现在是白名单模式 需要黑名单模式的触发ID

### ISSUE THREAD

**Issue by iceriny** [dynilath/BCResponsive#1]
- 有些动作自己触发的话也会弹出对应的反馈 非常奇怪
- 如果有黑名单模式的触发ID  就可以过滤掉黑名单中的玩家引起的反馈

**Comment by dynilath** [comment]
> * 有些动作自己触发的话也会弹出对应的反馈 非常奇怪

目前确实没有直接过滤掉对自己的触发，这段讲的太笼统了我没能理解你期待的程序行为是什么样的

**Comment by dynilath** [comment]
在 867809b 中实现
